#!/usr/bin/env python3
# protoc-gen-easyrpc-dart: read CodeGeneratorRequest, emit <file>_easyrpc.dart
# with METHOD table + strong-typed client. Dart messages come from protoc-gen-dart.
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            name=m.name or ''
            path=f'/{pkg}.{svc.name}/{name}'
            out.append((svc.name, name, path, m.server_streaming))
    return out

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        lines=['// Code generated by protoc-gen-easyrpc-dart. DO NOT EDIT.','', '// Method table', 'class EasyRpcMethods {', '  static const specs = <Map<String, dynamic>>[']
        for (svc,name,path,ss) in ms:
            lines.append(f"    {{'service': '{svc}', 'name': '{name}', 'path': '{path}', 'serverStream': {'true' if ss else 'false'}}},")
        lines.append('  ];')
        lines.append('}')
        lines.append('')
        # client: emit per-service function using generated pb types is complex;
        # emit a generic methodSpecs mirror. Keep it a table now.
        content='\n'.join(lines)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc.dart', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

if __name__=='__main__': main()
