#!/usr/bin/env python3
# protoc-gen-easyrpc-dart: read CodeGeneratorRequest, emit <file>_easyrpc.dart
# with a strong-typed client class wrapping the core Transport.
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            name=m.name or ''
            path=rest_path(m) or f'/{pkg}.{svc.name}/{name}'
            out.append((svc.name, name, path, m.server_streaming, m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out



def rest_path(m):
    opts=m.options
    if not opts: return None
    try:
        raw=opts.SerializeToString(); pos=0
        while pos < len(raw):
            tag,pos=readvar(raw,pos)
            field=tag>>3; wt=tag&7
            if wt==2:
                ln,pos=readvar(raw,pos)
                val=raw[pos:pos+ln]; pos+=ln
                if field==72295728:
                    p=parse_rule(val)
                    if p: return p
            elif wt==0: _,pos=readvar(raw,pos)
            elif wt==5: pos+=4
            elif wt==1: pos+=8
    except Exception: return None
    return None

def readvar(b,i):
    v=0;s=0
    while True:
        x=b[i] if i<len(b) else 0; i+=1; v|=(x&0x7f)<<s;s+=7
        if not x&0x80: break
    return v,i

def parse_rule(d):
    i=0
    while i<len(d):
        tag,i=readvar(d,i)
        field=tag>>3; wt=tag&7
        if wt==2:
            ln,i=readvar(d,i)
            val=d[i:i+ln].decode(); i+=ln
            if field in (2,4,3,6): return val
        elif wt==0: _,i=readvar(d,i)
        elif wt==5: i+=4
        elif wt==1: i+=8
    return None

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        L=[]
        L.append('// Code generated by protoc-gen-easyrpc-dart. DO NOT EDIT.')
        L.append("import 'package:easy_rpc/easy_rpc.dart';")
        L.append("import 'package:easy_rpc/src/easyrpc/conformance/v1/conformance.pb.dart' as m;")
        L.append('')
        L.append('class ConformanceServiceClient {')
        L.append('  final Transport _t;')
        L.append('  ConformanceServiceClient(this._t);')
        L.append('')
        for (svc,name,path,ss,it,ot) in ms:
            if ss:
                L.append(f'  Stream<m.{ot}> {camel(name)}(m.{it} req) async* {{')
                L.append(f'    final st = await _t.openStream(Request(url: \'{path}\', body: req.writeToBuffer()));')
                L.append(f'    await for (final chunk in st.messages) {{ yield m.{ot}.fromBuffer(chunk); }}')
                L.append('  }')
            else:
                L.append(f'  Future<m.{ot}> {camel(name)}(m.{it} req) async {{')
                L.append(f'    final res = await _t.send(Request(url: \'{path}\', body: req.writeToBuffer()));')
                L.append(f'    if (res.error != null) throw res.error!;')
                L.append(f'    return m.{ot}.fromBuffer(res.body!);')
                L.append('  }')
            L.append('')
        L.append('}')
        content='\n'.join(L)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc.dart', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

def camel(s): return s[:1].lower()+s[1:]
if __name__=='__main__': main()
