#!/usr/bin/env python3
# protoc-gen-easyrpc-dart: read CodeGeneratorRequest, emit <file>_easyrpc.dart
# with a strong-typed client class wrapping the core Transport.
#
# Package-aware: the import path, message alias and service class name are all
# derived from the proto, so any package (e.g. agent.v1, easyrpc.conformance.v1)
# can be generated instead of being hard-coded to conformance.
import os
import sys
from google.protobuf.compiler import plugin_pb2 as plugin


def resolve(f):
    out = []
    pkg = f.package or ''
    for svc in f.service:
        for m in svc.method:
            name = m.name or ''
            path = f'/{pkg}.{svc.name}/{name}'
            out.append((svc.name, name, path, m.server_streaming,
                        m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out



def readvar(b, i):
    v = 0
    s = 0
    while True:
        x = b[i] if i < len(b) else 0
        i += 1
        v |= (x & 0x7f) << s
        s += 7
        if not x & 0x80:
            break
    return v, i


def parse_rule(d):
    i = 0
    while i < len(d):
        tag, i = readvar(d, i)
        field = tag >> 3
        wt = tag & 7
        if wt == 2:
            ln, i = readvar(d, i)
            val = d[i:i + ln].decode()
            i += ln
            if field in (2, 4, 3, 6):
                return val
        elif wt == 0:
            _, i = readvar(d, i)
        elif wt == 5:
            i += 4
        elif wt == 1:
            i += 8
    return None


def main():
    data = sys.stdin.buffer.read()
    req = plugin.CodeGeneratorRequest.FromString(data)
    # --easyrpc-dart_out accepts `pb_root=` to locate the generated *_pb.dart.
    # Default mirrors the conformance layout: package:easy_rpc/src.
    pb_root = os.environ.get('EASYRPC_DART_PB_ROOT', 'package:easy_rpc/src')
    files = []
    for f in req.proto_file:
        if f.name not in req.file_to_generate:
            continue
        ms = resolve(f)
        if not ms:
            continue
        base = f.name[:-6]                 # strip .proto
        pkg_dir = os.path.dirname(f.name).replace('\\', '/')
        # pb file lives at <pb_root>/<pkg_dir>/<basename>.pb.dart.
        pb_import = f"{pb_root}/{pkg_dir}/{os.path.basename(base)}.pb.dart" if pkg_dir else f"{pb_root}/{os.path.basename(base)}.pb.dart"
        # One output file per SERVICE: the flat file would only emit the last
        # service's class, dropping the others.
        service_names = sorted({svc for (svc, _n, _p, _s, _i, _o) in ms})
        multi = len(service_names) > 1
        for svc_name in service_names:
            methods = [x for x in ms if x[0] == svc_name]
            client = svc_name + 'Client'
            L = []
            L.append('// Code generated by protoc-gen-easyrpc-dart. DO NOT EDIT.')
            L.append("import 'dart:typed_data';")
            L.append("import 'package:easy_rpc/easy_rpc.dart';")
            L.append(f"import '{pb_import}' as m;")
            L.append('')
            L.append(f'class {client} {{')
            L.append('  final Transport _t;')
            L.append(f'  {client}(this._t);')
            L.append('  Request _req(String url, [Uint8List? body]) => Request(url: url, body: body);')
            L.append('  Headers lastTrailers = const {};')
            L.append('  RpcStream? lastStream;')
            L.append('')
            for (svc, name, path, ss, it, ot) in methods:
                if ss:
                    L.append(f'  Stream<m.{ot}> {camel(name)}(m.{it} req) async* {{')
                    L.append(f"    final st = await _t.openStream(_req('{path}', Uint8List.fromList(frame(req.writeToBuffer()))));")
                    L.append('    lastStream = st;')
                    L.append(f'    await for (final chunk in st.messages) {{ yield m.{ot}.fromBuffer(chunk); }}')
                    L.append('  }')
                else:
                    L.append(f'  Future<m.{ot}> {camel(name)}(m.{it} req) async {{')
                    L.append(f"    final res = await _t.send(_req('{path}', req.writeToBuffer()));")
                    L.append('    if (res.error != null) throw res.error!;')
                    L.append('    lastTrailers = res.trailers;')
                    L.append(f'    return m.{ot}.fromBuffer(res.body!);')
                    L.append('  }')
                L.append('')
            L.append('}')
            suffix = ('_' + svc_name) if multi else ''
            content = '\n'.join(L)
            files.append(plugin.CodeGeneratorResponse.File(name=base + suffix + '_easyrpc.dart', content=content))
    resp = plugin.CodeGeneratorResponse(file=files)
    resp.supported_features = plugin.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL
    sys.stdout.buffer.write(resp.SerializeToString())


def camel(s):
    return s[:1].lower() + s[1:]


if __name__ == '__main__':
    main()
